# Generated by Django 5.2 on 2025-04-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
